#!/usr/bin/env node

const fs = require('fs')
const { exec } = require('child_process')


////////////////////////////////////////////////////////////////////////////////
/// Directories
////////////////////////////////////////////////////////////////////////////////

const DIR = __dirname,
      DIR_USER = process.cwd()


////////////////////////////////////////////////////////////////////////////////
/// Browsers
////////////////////////////////////////////////////////////////////////////////

const BROWSERS = ['chrome', 'firefox', 'safari']

const DEFAULT_BROWSER = 'safari'

let BROWSER = null


////////////////////////////////////////////////////////////////////////////////
/// Helpers
////////////////////////////////////////////////////////////////////////////////

function exit(msg) {
  console.error(msg)
  process.exit(1)
}

function watch(_, filename) {
  // Ignore Emacs dirty files
  if (filename.includes('#'))
    return

  console.log(`File changed: '${filename}'`)
  const script = `${DIR}/osascript/${BROWSER}`
  exec(`osascript ${script}`)
}


////////////////////////////////////////////////////////////////////////////////
/// Main
////////////////////////////////////////////////////////////////////////////////

function main(argv) {
  const dir = argv[2] || DIR_USER,
        browser = argv[3]

  if (!dir)
    exit('Gimme directory to watch')

  if (!fs.lstatSync(dir).isDirectory())
    exit(`${dir} is not a valid directory`)

  BROWSER = BROWSERS.includes(browser) ? browser : DEFAULT_BROWSER

  console.log(`Directory: ${dir}`)
  console.log(`Browser: ${BROWSER}`)

  fs.watch(dir, {recursive: true}, watch)
}

main(process.argv)
